# Generated by Django 2.0.6 on 2018-06-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Write_ups', '0002_auto_20180625_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write_up',
            name='content',
            field=models.TextField(),
        ),
    ]
