# Generated by Django 2.0.6 on 2018-06-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date uploaded')),
                ('title', models.CharField(max_length=64)),
                ('caption', models.CharField(max_length=256)),
                ('imgURL', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
