# Generated by Django 2.0.6 on 2018-06-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgURL',
            field=models.ImageField(upload_to='Pages/media/Products/'),
        ),
    ]
