# Generated by Django 2.0.6 on 2018-06-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20180628_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgURL',
            field=models.ImageField(upload_to='Products/'),
        ),
    ]
